# Generated by Django 5.0.1 on 2024-01-16 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_update'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Update',
            new_name='service',
        ),
    ]
