# Generated by Django 5.0.1 on 2024-01-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_enquiryform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiryform',
            name='services',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
