# Generated by Django 5.0.1 on 2024-01-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('author_position', models.CharField(max_length=100)),
                ('avatar_image', models.ImageField(upload_to='web/images/testimonial/')),
            ],
        ),
    ]
